name: shopsavvy
description: Discover, Shop, Repeat.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_functions: ^4.3.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.0
  go_router: ^8.2.0
  google_sign_in: ^6.1.4
  http: ^1.0.0
  linkedin_login: ^2.2.1
  shared_preferences: ^2.1.2
dependency_overrides:
  http: ^0.13.4
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo/
    - assets/facebook_logo/
    - assets/linkedin_logo/
    - assets/app_logo/
    - assets/icons/
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/font/SF Pro Display/SFProDisplay-Regular.ttf
        - asset: assets/font/SF Pro Display/SF-Pro-Display-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/font/SF Pro Display/SF-Pro-Display-Medium.ttf
          style: normal
          weight: 500
