name: shopsavvy
description: Discover, Shop, Repeat.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo/
    - assets/facebook_logo/
    - assets/linkedin_logo/
    - assets/app_logo/
    - assets/icons/
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/font/SF Pro Display/SFProDisplay-Regular.ttf
        - asset: assets/font/SF Pro Display/SF-Pro-Display-Bold.ttf
        - asset: assets/font/SF Pro Display/SF-Pro-Display-Medium.ttf
        - asset: assets/font/SF Pro Display/SF-Pro-Display-Regular.ttf
