// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBOUbgOKbVPg_APQkylhQkGW0K7MFE6U4',
    appId: '1:905631552727:android:366834cfc3dd76481e0c92',
    messagingSenderId: '905631552727',
    projectId: 'shopsavvy-7ac92',
    storageBucket: 'shopsavvy-7ac92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9e2TKsZbtIv8n9TXx9hv-9prvQkX4jTI',
    appId: '1:905631552727:ios:9edaf50f0a1669881e0c92',
    messagingSenderId: '905631552727',
    projectId: 'shopsavvy-7ac92',
    storageBucket: 'shopsavvy-7ac92.appspot.com',
    iosClientId:
        '905631552727-5jdanvchr9mha8vj2nob5mc6pqtbkqt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsavvy',
  );
}
